# Generated by Django 4.2.3 on 2023-07-04 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('concluido', 'Concluído'), ('em_manutencao', 'Em Manutenção'), ('pendente', 'Pendente')], max_length=20)),
                ('manutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.manutencao')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='item_photos')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='item_photos')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='item_photos')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atividade.atividade')),
            ],
        ),
    ]
