# Generated by Django 4.2.3 on 2023-07-06 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0003_areachoise_itemchoise'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemchoise',
            name='AreaChoise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='atividade.areachoise'),
            preserve_default=False,
        ),
    ]
