# Generated by Django 4.2.3 on 2023-07-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0006_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='checado',
            field=models.BooleanField(default=False),
        ),
    ]
